use_frameworks!

platform :ios, '9.0'

target 'AntDesignColor_Example' do
  pod 'AntDesignColor', :path => '../'

  target 'AntDesignColor_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
   end
  end
 end
 